### PR TITLE
Various additions/tests

### PR DESCRIPTION
**Pull request by zachallaun**
Hi there!

I've been sitting on these changes for a while now and thought that it was better to just make a pull request now. The biggest changes here are that 1) you no longer have to care about BSONObjects as a user and 2) there are more tests. I've also refactored a fair bit of the code to make it more Julian.

Thanks for making this in the first place! Cheers.

### CODE REVIEW

**Comment by Lytol** [comment]
Heyo, this is awesome! I like the test framework you're using, and replacing `BSONObject` with a `Dict` abstraction is a very welcome change – developers shouldn't need to know anything about `BSONObject` to simply use the Mongo library. One quick thing before I merge:
- `FactCheck` and `immutable Sentinel end` both put us in the Julia 0.2+ category. I don't have a problem with this, but I wanted to make sure this was intentional and acknowledged.

I'll merge and update the README accordingly, just let me know your opinion on 0.2+.

**Comment by zachallaun** [comment]
Ah, good point! Yes, I developed this assuming `julia 0.2-`. I've codified that in an update to `REQUIRE`. I'm not sure what kind of note you'd like in the README, so I'll let you handle that bit. :)

**Comment by zachallaun** [comment]
Hi there @Lytol! Is there anything else I can do to help get this merged? (Totally understand if you've been busy.)

**Comment by Lytol** [comment]
Sorry, it's taken too long – you've done more than enough, I'll have it
merged by end of the week. Thanks again for the contribution!

On Wed, Oct 2, 2013 at 12:49 PM, Zach Allaun notifications@github.comwrote:

> Hi there @Lytol https://github.com/Lytol! Is there anything else I can
> do to help get this merged? (Totally understand if you've been busy.)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Lytol/Mongo.jl/pull/18#issuecomment-25570872
> .

## 

Brian Smith
(858) 527-8825

**Comment by zachallaun** [comment]
Awesome, thanks so much :)

**Pull request merged**
